[package]
name = "infra-utils"
version = "0.1.0"
authors = ["sutr-app"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "1.0"
async-trait = "0.1"
chrono = "0.4"
command-utils = { git = "https://github.com/sutr-app/command-utils.git", tag = "v0.1.0" }
deadpool = { version = "0.10", features = ["rt_tokio_1"] }
deadpool-redis = { version = "0.14", features = ["rt_tokio_1", "cluster"] }
debug_stub_derive = "0.3"
envy = "0.4"
futures = "0.3"
log = "0.4"
once_cell = "1.19"
opentelemetry = { version = "0.21", features = ["metrics", "trace"] }
redis = { version = "0.24", features = [
    "tokio-rustls-comp",
    "r2d2",
    "ahash",
    "cluster-async",
] }
serde = "1.0"
serde_json = "1.0"
sqlx = { version = "0.6", features = [
    "runtime-tokio-native-tls",
    "any",
    "sqlite",
    "mysql",
    "macros",
    "chrono",
] }
stretto = { version = "0.8", features = ["async"] }
tonic = { version = "0.10" }
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
    "process",
    "parking_lot",
] }
tracing = "0.1"
unicode-normalization = "0.1"

[dev-dependencies]
itertools = "0.12"

[features]
default = []
redis-test = []
redis-cluster-test = []
